apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: virtualmachines.doslab.io
spec:
  group: doslab.io
  names:
    kind: VirtualMachine
    plural: virtualmachines
    shortNames:
      - vm
      - vms
    singular: virtualmachine
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - jsonPath: .spec.domain.uuid.text
          name: UUID
          type: string
        - jsonPath: .spec.domain._type
          name: TYPE
          type: string
        - jsonPath: .spec.domain.vcpu._current
          name: CPU
          type: string
        - jsonPath: .spec.domain.currentMemory.text
          name: RAM(KB)
          type: string
        - jsonPath: .spec.powerstate
          name: STATUS
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: AGE
          type: date
        - jsonPath: .spec.nodeName
          name: NODE
          type: string
        - jsonPath: .spec.status.conditions.state.waiting.reason
          name: MESSAGE
          type: string
        - jsonPath: .spec.image
          name: IMAGE
          type: string