apiVersion: v1
kind: ServiceAccount
metadata:
  name: label-hook-sa
  labels:
    app: label-hook

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: label-hook-cr
  labels:
    app: label-hook
rules:
  - apiGroups:
      - doslab.io
    resources:
      - "*"
    verbs:
      - "*"

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: label-hook-crb
  labels:
    app: label-hook
subjects:
  - kind: ServiceAccount
    name: label-hook-sa
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: label-hook-cr